### ISSUE TITLE
Slideover: Tags

### ISSUE THREAD

**Issue by AitchGrasso** [snowballDevs/kandoo#110]
### Description

Add tag(s) to task. 

### Proposed Solution (for features)

Make tags section only accessible upon Editmode. The selected tag should appear either in the slideover header or in the section it is currently in. 

### Additional Context (optional)

![image](https://github.com/snowballDevs/kandoo/assets/119631464/a0d14606-bd5d-40c5-9df4-b1b3116217d2)

**Comment by IntelliJinceTech** [comment]
This wil be tackled in my upcoming PR alongside comments
