### ISSUE TITLE
Task Card: UI - taskName and Tag

### ISSUE THREAD

**Issue by AitchGrasso** [snowballDevs/kandoo#113]
### Description

The task card should have the Task's name and accent color (high med low). The task card should also re-render with updated task info when updated through slideover. 

Accent: 
![Image](https://github.com/snowballDevs/kandoo/assets/52391491/b8b7a07b-b5e5-47b0-bb11-16bd04675033)

- Should also have assigned users and should show similar presentation to github - but have the user bubbles shown not on top of each other.

### Proposed Solution (for features)

This may require moving formData to the card component from the slider component

### Additional Context (optional)

[Add any additional information or context about the issue or feature]

### Tasks (optional)

-   [ ] Task 1
-   [ ] Task 2

### Related Issues or PRs (optional)

[If there are any related issues or pull requests, link them here]

**Comment by IntelliJinceTech** [comment]
Potential Bug in PR - when clicking on task, the task card CSS is inconsistent with the taskcard sizing prior to clicking.
