### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by AitchGrasso** [snowballDevs/kandoo#4]
- [x] tim
Referances from Tim: 
[](https://mongoosejs.com/docs/subdocs.html)
[](https://www.mongodb.com/blog/post/6-rules-of-thumb-for-mongodb-schema-design)
- [x] User
- [x] Board
- [x] Tasks
- [x] Comments

**Comment by AitchGrasso** [comment]
![Image](https://user-images.githubusercontent.com/119631464/236977897-55d3084e-dba1-4354-ae18-d598b0b8de54.png)

**Comment by IntelliJinceTech** [comment]
Revised Schema from Tim's feedback



![Image](https://github.com/snowballDevs/kandoo/assets/52391491/a8f2adf9-6b27-42a9-9be0-fd51a9fd7833)
