### ISSUE TITLE
Get rid of scroll bar on App so that you don't need to scroll for the footer

### ISSUE THREAD

**Issue by IntelliJinceTech** [snowballDevs/kandoo#44]
### Description
Remove the scroll bar on the app so that you don't need to scroll down the page to see the footer. Everything should be available without needing to scroll.

### Current Behavior (for bugs)

Landing Page (e.g.) currently has an unnecessary scroll bar. 

### Expected Behavior (for bugs)

Landing Page should have no scroll bar except later in our columns in boards. 

### Proposed Solution (for features)
Remove it!

### Related Issues or PRs (optional)

[If there are any related issues or pull requests, link them here]

**Comment by carlykiang** [comment]
Interested in working on this issue!

**Comment by AitchGrasso** [comment]
As far as I can tell there isn't a scroll bar. Good to close the issue?
