### ISSUE TITLE
Create Kandoo Logo

### ISSUE THREAD

**Issue by mjbramich** [snowballDevs/kandoo#45]
### Description

Create a kandoo logo, (be as creative as you wish)

**Comment by isomer04** [comment]
![kandoo-logo](https://github.com/snowballDevs/kandoo/assets/43922158/e7dabf2d-dcc3-4a22-a7d5-8106f9751676)
 How is this one?

**Comment by isomer04** [comment]
![kandoo-logo (1)](https://github.com/snowballDevs/kandoo/assets/43922158/cd968568-100f-4214-bd22-98e1b2e8eb25)

**Comment by isomer04** [comment]
![kandoo-logo (2)](https://github.com/snowballDevs/kandoo/assets/43922158/f8a13169-fc55-4408-b991-29cd8bd877fa)

**Comment by mjbramich** [comment]
![Kandoo](https://github.com/snowballDevs/kandoo/assets/105207353/99a4aa8a-5b07-4c9b-bc5a-a28ad6b422bf)
