### ISSUE TITLE
Change Document Title and Icon

### ISSUE THREAD

**Issue by IntelliJinceTech** [snowballDevs/kandoo#46]
### Description

Change Document Title and Icon Logo

### Proposed Solution (for features)

Change the `Vite + React + TS` and logo to something more app-oriented.

### Tasks (optional)

-   [ ] Change the Document Title
-   [ ] Change the Document Logo

### Related Issues or PRs (optional)

[If there are any related issues or pull requests, link them here]

**Comment by promise-dash** [comment]
Hey, I would like to resolve this issue.
Could you please assign me this?

**Comment by isomer04** [comment]
> Hey, I would like to resolve this issue. Could you please assign me this?

Sorry. This is a group project with assigned people. Currently, we are not accepting any more members.
