### ISSUE TITLE
Column CSS (Frontend)

### ISSUE THREAD

**Issue by IntelliJinceTech** [snowballDevs/kandoo#82]
### Description

proposing for the frontend that we limit to 4 columns. Column form can come post-mvp.

### Current Behavior (for bugs)

[Describe what is currently happening or the problem you're facing]

### Expected Behavior (for bugs)

[Describe what you expected to happen]

### Proposed Solution (for features)

[Describe your proposed solution or implementation for the feature]

### Additional Context (optional)

[Add any additional information or context about the issue or feature]

### Tasks (optional)

-   [ ] Task 1
-   [ ] Task 2

### Related Issues or PRs (optional)

[If there are any related issues or pull requests, link them here]

**Comment by AitchGrasso** [comment]
Some current issues with the column

- [ ] Newly added task is not editable 
- [ ] Task counters do not currently work

**Comment by AitchGrasso** [comment]
Closed with #93
